version: '3.7'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - .env_db

  web:
    image: zhss1983/api_yamdb:v-3
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - .env_db
      - .env_mail
      - .env_web

  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: 127.0.0.1
      SERVERNAME: www.zhss.tk
      EXTRANAMES: zhss.tk
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    env_file:
      - .env_nginx

volumes:
  static_value:
  media_value:
