version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    env_file:
      - .env_db

  web:
    image: zhss1983/api_yamdb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - .env_db
      - .env_mail
      - .env_web

  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf/:/etc/letsencrypt/
      - ./data/certbot/www/:/var/www/certbot/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: service_certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_value:
  media_value:
